language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS tickettest;'
# command to install dependencies
install:
    - pip install -r requirements.txt
    
script:
    python manage.py test
