# Generated by Django 3.1.1 on 2020-11-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airplane',
            fields=[
                ('airplaneId', models.AutoField(primary_key=True, serialize=False)),
                ('craftTypeCode', models.IntegerField(null=True)),
                ('airlineName', models.CharField(max_length=20, null=True)),
                ('craftType', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=20, null=True)),
                ('site', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flightId', models.AutoField(primary_key=True, serialize=False)),
                ('flightNumber', models.CharField(max_length=20, null=True)),
                ('dcityNum', models.CharField(max_length=20, null=True)),
                ('acityNum', models.CharField(max_length=20, null=True)),
                ('dcityName', models.CharField(max_length=20, null=True)),
                ('acityName', models.CharField(max_length=20, null=True)),
                ('departureTime', models.DateField(null=True)),
                ('arrivalTime', models.DateField(null=True)),
                ('departureAirportName', models.CharField(max_length=20, null=True)),
                ('arrivalAirportName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateTimeField(null=True)),
                ('arrivalDate', models.DateTimeField(null=True)),
                ('dairport', models.CharField(max_length=50, null=True)),
                ('aairport', models.CharField(max_length=50, null=True)),
                ('flightNumber', models.CharField(max_length=20)),
                ('dcity', models.CharField(max_length=20)),
                ('dcityName', models.CharField(max_length=20, null=True)),
                ('acity', models.CharField(max_length=20)),
                ('acityName', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('dtime', models.TimeField(null=True)),
                ('atime', models.TimeField(null=True)),
                ('airplaneId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketModel.airplane')),
                ('companyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketModel.company')),
                ('flightId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketModel.flight')),
            ],
        ),
    ]
