# Generated by Django 3.1.1 on 2020-12-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketModel', '0002_tickets_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcityName', models.CharField(max_length=50, null=True)),
                ('acityName', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('saveDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
