# Generated by Django 3.1.1 on 2020-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketModel', '0003_companyticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyticket',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
