# Generated by Django 3.1.1 on 2020-12-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketModel', '0004_companyticket_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyticket',
            old_name='company',
            new_name='companyName',
        ),
    ]
