# Generated by Django 3.1.1 on 2020-12-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernflight',
            name='orgPrice',
            field=models.IntegerField(null=True),
        ),
    ]
